const pronouns = ["She/Her", "He/Him", "They/Them", "Other"];

const genders = ["Woman", "Man", "Nonbinary", "Other"];

const sexualities = [
    "Straight",
    "Gay",
    "Lesbian",
    "Bisexual",
    "Asexual",
    "Demisexual",
    "Queer",
    "Skoliosexual",
    "Fluid",
    "Questioning",
    "Other",
];

const countries = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Andorra",
    "Angola",
    "Antigua and Barbuda",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahamas",
    "Bahrain",
    "Bangladesh",
    "Barbados",
    "Belarus",
    "Belgium",
    "Belize",
    "Benin",
    "Bhutan",
    "Bolivia",
    "Bosnia and Herzegovina",
    "Botswana",
    "Brazil",
    "Brunei",
    "Bulgaria",
    "Burkina Faso",
    "Burundi",
    "Côte d'Ivoire",
    "Cabo Verde",
    "Cambodia",
    "Cameroon",
    "Canada",
    "Central African Republic",
    "Chad",
    "Chile",
    "China",
    "Colombia",
    "Comoros",
    "Congo (Congo-Brazzaville)",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Cyprus",
    "Czechia (Czech Republic)",
    "Democratic Republic of the Congo",
    "Denmark",
    "Djibouti",
    "Dominica",
    "Dominican Republic",
    "Ecuador",
    "Egypt",
    "El Salvador",
    "Equatorial Guinea",
    "Eritrea",
    "Estonia",
    "Eswatini (fmr. 'Swaziland')",
    "Ethiopia",
    "Fiji",
    "Finland",
    "France",
    "Gabon",
    "Gambia",
    "Georgia",
    "Germany",
    "Ghana",
    "Greece",
    "Grenada",
    "Guatemala",
    "Guinea",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Holy See",
    "Honduras",
    "Hungary",
    "Iceland",
    "India",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Jamaica",
    "Japan",
    "Jordan",
    "Kazakhstan",
    "Kenya",
    "Kiribati",
    "Kuwait",
    "Kyrgyzstan",
    "Laos",
    "Latvia",
    "Lebanon",
    "Lesotho",
    "Liberia",
    "Libya",
    "Liechtenstein",
    "Lithuania",
    "Luxembourg",
    "Madagascar",
    "Malawi",
    "Malaysia",
    "Maldives",
    "Mali",
    "Malta",
    "Marshall Islands",
    "Mauritania",
    "Mauritius",
    "Mexico",
    "Micronesia",
    "Moldova",
    "Monaco",
    "Mongolia",
    "Montenegro",
    "Morocco",
    "Mozambique",
    "Myanmar (formerly Burma)",
    "Namibia",
    "Nauru",
    "Nepal",
    "Netherlands",
    "New Zealand",
    "Nicaragua",
    "Niger",
    "Nigeria",
    "North Korea",
    "North Macedonia",
    "Norway",
    "Oman",
    "Pakistan",
    "Palau",
    "Palestine State",
    "Panama",
    "Papua New Guinea",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Qatar",
    "Romania",
    "Russia",
    "Rwanda",
    "Saint Kitts and Nevis",
    "Saint Lucia",
    "Saint Vincent and the Grenadines",
    "Samoa",
    "San Marino",
    "Sao Tome and Principe",
    "Saudi Arabia",
    "Senegal",
    "Serbia",
    "Seychelles",
    "Sierra Leone",
    "Singapore",
    "Slovakia",
    "Slovenia",
    "Solomon Islands",
    "Somalia",
    "South Africa",
    "South Korea",
    "South Sudan",
    "Spain",
    "Sri Lanka",
    "Sudan",
    "Suriname",
    "Sweden",
    "Switzerland",
    "Syria",
    "Tajikistan",
    "Tanzania",
    "Thailand",
    "Timor-Leste",
    "Togo",
    "Tonga",
    "Trinidad and Tobago",
    "Tunisia",
    "Turkey",
    "Turkmenistan",
    "Tuvalu",
    "Uganda",
    "Ukraine",
    "United Arab Emirates",
    "United Kingdom",
    "United States of America",
    "Uruguay",
    "Uzbekistan",
    "Vanuatu",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
    "Zimbabwe"
  ];
  

const interestList = [
    "Cooking",
    "Traveling",
    "Reading",
    "Hiking",
    "Photography",
    "Painting",
    "Music",
    "Dancing",
    "Yoga",
    "Gardening",
    "Writing",
    "Coding",
    "Gaming",
    "Movies",
    "Woodworking",
    "Fashion",
    "DIY",
    "Language",
    "Exercising",
    "Running",
    "Swimming",
    "Fishing",
    "Skydiving",
    "Skiing",
    "Surfing",
    "Camping",
    "Volunteer",
    "Astrology",
    "Chess",
    "Board games",
    "Mixology",
    "Travel",
    "Stargazing",
    "Podcast",
    "Tattoo",
    "Weightlift",
    "Cycling",
    "Bungee",
    "Surfing",
    "Ice skating",
    "Skateboarding",
    "Escape rooms",
    "Zoology",
    "Astronomy",
    "Astrophotography",
    "Ghost hunting",
    "Mythology",
    "Magic tricks",
    "Poker",
    "Billiards",
    "Bowling",
    "Golf",
    "Tennis",
    "Badminton",
    "Volleyball",
    "Basketball",
    "Football",
    "Soccer",
    "Rugby",
    "Cricket",
    "Baseball",
    "Hockey",
    "Boxing",
    "Martial arts",
    "Jiu-jitsu",
    "Wrestling",
    "Fencing",
    "Kickboxing",
    "Muay Thai",
    "Gymnastics",
    "Crossfit",
    "Calisthenics",
    "Mountain biking",
    "Trail running",
    "Ultra running",
    "Open water swimming",
    "Diving",
];

// eslint-disable-next-line no-undef
module.exports = {pronouns, genders, sexualities, countries, interestList};